# -*- coding: utf-8 -*-
"""Assignment13 IMDb_Week_Long_Pandas_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZEd1J9cGgnj3uCkjOWHvU-sILsDmaKuX

# IMDb Dataset - Assignment

Complete all questions during the week. Write your solutions below each question.

### Question 1
Load the IMDb dataset using Pandas.
"""

# Write your solution here
import pandas as pd
df = pd.read_csv('/imdb_data.csv')
df.head()

"""### Question 2
Display the first 10 rows of the dataset.
"""

# Write your solution here
df.head(10)

"""### Question 3
Display the last 10 rows of the dataset.
"""

# Write your solution here
df.tail(10)

"""### Question 4
Find the total number of rows and columns in the dataset.
"""

# Write your solution here
df.shape

"""### Question 5
Display all column names.
"""

# Write your solution here
df.columns

"""### Question 6
Check the data types of all columns.
"""

# Write your solution here
df.info()

"""### Question 7
Find the total number of missing values in each column.
"""

# Write your solution here
df.isnull().sum()

"""### Question 8
Generate summary statistics using describe().
"""

# Write your solution here
df.describe()

"""### Question 1
Display rows 10 to 20 and columns 2 to 5 using iloc.
"""

# Write your solution here
df.iloc[10:20,2:5]

"""### Question 2
Display the first 15 rows using iloc.
"""

# Write your solution here
df.iloc[:15,:]

"""### Question 3
Extract only the columns: title, budget, revenue using loc.
"""

# Write your solution here
df.loc[:,['title', 'budget', 'revenue']]

"""### Question 4
Display only the title and runtime columns.
"""

# Write your solution here
df.loc[:,['title','runtime']]

"""### Question 5
Extract the last 20 rows of the dataset.
"""

# Write your solution here
df.tail(20)

"""### Question 6
Display rows 50 to 100 with only title and popularity columns.
"""

# Write your solution here
df.loc[50:100,['popularity']]

"""### Question 1
Find all movies whose original language is English (en).
"""

# Write your solution here
df[df['original_language']== 'en']

"""### Question 2
Find all movies whose original language is Hindi (hi).
"""

# Write your solution here
df[df['original_language']== 'en']

"""### Question 3
Display only the title and original_language columns for Hindi movies.
"""

# Write your solution here
df[df['original_language']== 'hi'][['title','original_language']]

"""### Question 4
Find movies having a budget greater than 100 million.
"""

# Write your solution here
df[df['budget']>100000000]

"""### Question 5
Find movies with revenue greater than 500 million.
"""

# Write your solution here
df[df['revenue']>500000000]

"""### Question 6
Find movies whose runtime is greater than 150 minutes.
"""

# Write your solution here
df[df['runtime']>150]

"""### Question 7
Find movies with popularity greater than the average popularity.
"""

# Write your solution here
popularity_average = df['popularity'].mean()
print(popularity_average)
df[df['popularity']>popularity_average]

"""### Question 1
Create a new column called half_runtime.
"""

# Write your solution here
df['half_runtime'] = df['runtime']/2
df.head()

"""### Question 2
Create a new column called double_runtime.
"""

# Write your solution here
df['double_runtime'] = df['runtime']*2
df.head()

"""### Question 3
Create a new column called profit = revenue - budget.
"""

# Write your solution here
df['Profit'] = df['revenue'] - df['budget']
df.head()

"""### Question 4
Create a new column called profit_percentage.
"""

# Write your solution here
df['profit_percentage'] = (df['Profit']/df['budget'])*100
df.head()

"""### Question 5
Create a column named budget_in_crores.
"""

# Write your solution here
df['budget_in_crores'] = df['budget']/10000000
df.head()

"""### Question 6
Create a column named runtime_hours.
"""

# Write your solution here
df['runtime_hours'] = df['runtime']/60
df.head()

"""### Question 1
Find the maximum profit.
"""

# Write your solution here
df['Profit'].max()

"""### Question 2
Find the minimum profit.
"""

# Write your solution here
df['Profit'].min()

"""### Question 3
Find the average profit.
"""

# Write your solution here
df['Profit'].mean()

"""### Question 4
Find the median profit.
"""

# Write your solution here
df['Profit'].median()

"""### Question 5
Find the mode of profit.
"""

# Write your solution here
df['Profit'].mode()

"""### Question 6
Find the total profit generated by all movies.
"""

# Write your solution here
df['Profit'].sum()

"""### Question 7
Find the maximum runtime.
"""

# Write your solution here
df['runtime'].max()

"""### Question 8
Find the minimum runtime.
"""

# Write your solution here
df['runtime'].min()

"""### Question 9
Find the average runtime.
"""

# Write your solution here
df['runtime'].mean()

"""### Question 10
Find the movie having the highest revenue.
"""

# Write your solution here
df[df['revenue']==df['revenue'].max()]

"""### Question 11
Find the movie having the lowest budget.
"""

# Write your solution here
df[df['budget']==df['budget'].min()]

"""### Question 1
List the top 10 movies by revenue.
"""

# Write your solution here
movies = df.sort_values(by = 'revenue', ascending = False)
movies.head(10)

"""### Question 2
List the top 10 movies by profit.
"""

# Write your solution here
movies = df.sort_values(by = 'Profit', ascending = False)
movies.head(10)

"""### Question 3
List the top 10 movies by popularity.
"""

# Write your solution here
movies = df.sort_values(by = 'popularity', ascending = False)
movies.head(10)

"""### Question 4
Find the 10 longest movies.
"""

# Write your solution here
movies = df.sort_values(by = 'runtime', ascending = False)
movies.head(10)

"""### Question 5
Find the 10 shortest movies.
"""

# Write your solution here
movies = df.sort_values(by = 'runtime', ascending = True)
movies.head(10)

"""### Question 6
Find the total number of movies available in each language.
"""

# Write your solution here
df['original_language'].value_counts()

"""### Question 7
Find the language with the highest number of movies.
"""

# Write your solution here
df['original_language'].value_counts().head(1)

"""### Question 8
Find the average runtime for each language.
"""

# Write your solution here
df.groupby('original_language')['runtime'].mean()

"""### Question 9
Find the average profit for each language.
"""

# Write your solution here
df.groupby('original_language')['Profit'].mean()

"""### Question 1
Find the movie with the highest profit percentage.
"""

filtered_df = df[df["budget"] != 0]

filtered_df[filtered_df["profit_percentage"] == filtered_df["profit_percentage"].max()]

"""### Question 2
Find movies that earned more than 5 times their budget.
"""

# Write your solution here
filtered_df = df[df["budget"] != 0]

filtered_df[filtered_df["revenue"] > filtered_df['budget']*5]

"""### Question 3
Find movies that resulted in a loss.
"""

# Write your solution here
filtered_df = df[df["budget"] != 0]

filtered_df[filtered_df["Profit"]<0]

"""### Question 4
Calculate the percentage of profitable movies.
"""

# Write your solution here
filtered_df = df[df["budget"] != 0]
profitable_percentage = (filtered_df[filtered_df["Profit"] > 0].shape[0] / df.shape[0]) * 100
print(profitable_percentage)

"""### Question 5
Calculate the percentage of loss-making movies.
"""

# Write your solution here
filtered_df = df[df["budget"] != 0]
profitable_percentage = (filtered_df[filtered_df["Profit"] < 0].shape[0] / df.shape[0]) * 100
print(profitable_percentage)

"""### Question 6
Find the top 5 most profitable Hindi movies.
"""

# Write your solution here
df.sort_values(by = 'Profit', ascending=False).head(5)

"""### Question 7
Find the top 5 most profitable English movies.
"""

# Write your solution here
df[df["original_language"] == "en"].sort_values(by="Profit", ascending=False).head(5)

"""### Question 8
Find all movies with runtime between 120 and 180 minutes.
"""

# Write your solution here
df[(df["runtime"] >= 120) & (df["runtime"] <= 180)]

"""### Question 9
Find movies with revenue greater than 1 billion.
"""

# Write your solution here
df[df['revenue']>1000000000]

"""### Question 10
Create a report showing Total Movies, Average Budget, Average Revenue, Average Profit, Maximum Profit, Minimum Profit.
"""

# Write your solution here
report = pd.DataFrame({
    "Total Movies": [df.shape[0]],
    "Average Budget": [df["budget"].mean()],
    "Average Revenue": [df["revenue"].mean()],
    "Average Profit": [df["Profit"].mean()],
    "Maximum Profit": [df["Profit"].max()],
    "Minimum Profit": [df["Profit"].min()]
})
report

"""### Question 11
Create a final summary dashboard using Pandas.
"""

# Write your solution here
import matplotlib.pyplot as plt

metrics = [
    "Total Movies",
    "Avg Budget",
    "Avg Revenue",
    "Avg Profit",
    "Max Profit",
    "Min Profit"
]

values = [
    df.shape[0],
    df["budget"].mean(),
    df["revenue"].mean(),
    df["Profit"].mean(),
    df["Profit"].max(),
    df["Profit"].min(),
]

plt.figure(figsize=(10,6))
plt.bar(metrics, values)

plt.title("Movie Dataset Summary Dashboard")
plt.xlabel("Metrics")
plt.ylabel("Values")
plt.xticks(rotation=20)

plt.show()