# -*- coding: utf-8 -*-
"""Assignment 7 - List Comprehension.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e7rF2R_GIM_Jwja07udNheK77tw4jdaG

# <u>Problem 1</u>

## The price of a house depends upon a lot of factors. These factors could be the geography, the area of house, the number of bedrooms in the house, proximity to necessary amenities etc. A simplistic model would assume that the price of a house depends on a single factor let's say area of the house.

## You are given a dictionary where the keys correspond to the area of a house (in sq. ft) and the value for each key is the price of the house (in lakh ₹) of 6 houses of a certain locality in Bengaluru
"""

# Dictionary of house area and house prices of 6 houses in
house_area_price_dict = {1056 : 39, 2600 : 120 , 1520 : 95, 1200 : 50, 2700 : 200, 1100 : 40}

"""### The values of this dictionary are actual prices. You want to make a simple model which takes the house area as input and outputs the predicted price.

### This model can be written as : <b><code>predicted_price(area) = 0.05*area + 10</code></b>

## Using the concept of list comprehension, create a list of predicted house prices using the above formula
"""

# Create a list of house areas
house =[0.05*i+10 for i in house_area_price_dict]
print(f"List of predicted house prices: {house}")
# Use list comprehension to store the predicted house prices in a list
# Print the list of predicted house prices

"""## Create another list which contains the squares of differences of each element of the two price lists : the actual prices and the predicted prices

"""

# List of actual house prices
actual_prices = list(house_area_price_dict.values())
# Create a list of tuples
difference_of_prices = list(zip(actual_prices,house))
diff = [(i-j)**2 for i,j in difference_of_prices]
# List of squared differences between each element of the two lists
print(f"Square of differences: {diff}")

"""# <u> Problem 2</u>

## You are given a sentence : <code>"I have been walking and running and dancing and smiling and laughing all my life, yet it all seems pointless."</code>

## You are required to extract all those words from this sentence in a list which ends with <code>ing</code>
"""

# Your sentence
my_sentence = "I have been walking and running and dancing and smiling and laughing all my life, yet it all seems pointless."

# Using list comprehension, extract those words which ends with ing
words = [ i for i in my_sentence.split(" ") if i[-3:]=='ing']
# Words ending with ing
print(words)

"""# <u> Problem 3</u>

#### Natural Language Processing or NLP is one of the most promising fields in Machine Learning. Most of the times in NLP we deal with the textual data (a bunch of strings). Sometimes when we are processing the text, it is a common practice to get rid of some set of stop words from our original text. By default stop words are very common words used in English language such as and, or, punctuations etc.

#### In this exercise, you are provided with a default set of stop words and you need to add some extra set of custom words and remove these words from the given sentence and obtain the sentence without the stop words
"""

# A sample sentence
sentence = 'Hello good morning folks! Today we will announce the half yearly performance results of the company. Due to the ongoing COVID-19 pandemic, our profits have declined by 60% as compared to the last year'

# Print your sentence
print(sentence)

# Default set of stop words
stop_words = {"i", "me", "my", "myself", "we", "our", "ours", "ourselves", "you", "your", "yours", "yourself",
              "yourselves", "he", "him", "his", "himself", "she", "her", "hers", "herself", "it", "its", "itself",
              "they", "them", "their", "theirs", "themselves", "what", "which", "who", "whom", "this", "that",
              "these", "those", "am", "is", "are", "was", "were", "be", "been", "being", "have", "has", "had",
              "having", "do", "does", "did", "doing", "a", "an", "the", "and", "but", "if", "or", "because",
              "as", "until", "while", "of", "at", "by", "for", "with", "about", "against", "between", "into",
              "through", "during", "before", "after", "above", "below", "to", "from", "up", "down", "in", "out",
              "on", "off", "over", "under", "again", "further", "then", "once", "here", "there", "when", "where",
              "why", "how", "all", "any", "both", "each", "few", "more", "most", "other", "some", "such", "no",
              "nor", "not", "only", "own", "same", "so", "than", "too", "very", "s", "t", "can", "will", "just",
              "don", "should", "now"}

# Update the set of stop words by adding the custom stop words
custom_stop_words = ["hello","good","morning","half","year"]
stop_words = list(stop_words)
stop_words.extend(custom_stop_words)
# Your code here
# Print the stop words in a sorted manner
print(sorted(stop_words))

# Create the list of words in the given sentence.
words = sentence.lower().split(" ")
print(words)

# Use list comprehension to remove the set of updated stop words from the list of words
wordnew = [i for i in words if i not in stop_words]
print(wordnew)

# Finally using the join() method, get the sentence without the stop words. Keep in mind that every word in the sentence will be separated by space
modified_sentence = " ".join(wordnew)
print(modified_sentence)
# Print the modified sentence