# -*- coding: utf-8 -*-
"""Assignment11- Introduction to Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/190uSvdB0llFtOGgXdNklifLP0cjBmHdB

# <u> Use only those concepts which have been taught till now </u>
"""

import numpy as np
import pandas as pd

"""# <u>**Problem 1**</u>

### You are given a list of urls. You need to extract the domain name from the urls in another list. Also you need to extract the ending string which the url ends with.

### For example, https://www.example.com/market.php -- In this example, domain name is <code>www.example.com</code> and the ending string is <code>php</code>


"""

# List of urls
url_list = ['https://blog.hubspot.com/marketing/parts-url',
            'https://www.google.com/enrollments',
            'https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rename.html',
            'https://www.programiz.com/python-programming/list']

# Extract the domains and the ending string. Hint : use the split method for a string
# List of urls
url_list = [
    'https://blog.hubspot.com/marketing/parts-url',
    'https://www.google.com/enrollments',
    'https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rename.html',
    'https://www.programiz.com/python-programming/list'
]
domains = []
endings = []
for url in url_list:
    # Extract domain name
    domain = url.split('/')[2]
    domains.append(domain)
    # Extract ending string
    last_part = url.split('/')[-1]
    ending = last_part.split('.')[-1]
    endings.append(ending)
print("Domains:", domains)
print("Ending Strings:", endings)

"""## Next create a pandas dataframe with the above three lists."""

import pandas as pd

df

import pandas as pd
# Create the DataFrame
df = pd.DataFrame({
    "Url": url_list,
    "Domain": domains,
    "Ending_string": endings
})
# Display the DataFrame
print(df)