# -*- coding: utf-8 -*-
"""Assignment4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i-Gk3QfTsdsIxqzRUar7hTJr3gefS_Fh

#**Assignment 4**

**Question 1:**

As an analyst, you had to present the quarterly performance results of your client. The data which you were provided was on daily basis. To complete this task, you needed to extract the quarter from a given date.

For example:

if the date lies between 1st Jan, 2020 - 31st March, 2020, you need to extract the corresponding quarter as '2020-Q1'

if the date lies between 1st April, 2020 - 30th June, 2020, the extracted quarter will be '2020-Q2'

if the date lies between 1st July, 2020 - 30th September, 2020, the extracted quarter will be '2020-Q3'

if the date lies between 1st October, 2020 - 31st Decemeber, 2020 then the extracted quarter will be '2020-Q4'
"""

# Take a proper date input from the user in the format YYYY-MM-DD. Consider this date as a string
user_date = '2020-12-20'
date_year=user_date[:4]
date_month = int(user_date[5:7])
# Write your code using if else statements to extract the quarter
if date_month<=3:
  quarter=date_year+'-Q1'
elif date_month<=6:
  quarter=date_year+'-Q2'
elif date_month<=9:
  quarter=date_year+'Q3'
else:
  quarter=date_year+'-Q4'
print(quarter)

"""**Question 2:**

You went out in your local neighbourhood to collect the data of people residing in the locale. You surveyed 5 people and collected some data and stored that in a dictionary. You recorded their names, their age, their gender, their heights(in cms) and their weights(in kgs)
"""

# Surveyed data

locality_data = {'Name' : ['Abhinav','Sohail','Dheeraj','Rashmi','Vaishali'],
                  'Age' : [42,29,35,28,32],
                  'gender' : ['Male', 'Female','Male','Female','Female'] ,
                  'Height' : [172,175,170,168,170],
                  'Weight' : [70,82,60,55,64]
                 }

Height = locality_data['Height']
Height

"""* Find the mean and median heights and weights of the people in your locality"""

# Calculate the mean height and print it
mean = sum(Height)/n
print(f"Mean of Height: {mean}")
Height = sorted(Height)
# Calculate the median height and print it
if n%2!=0:
  median = Height[((n+1)//2)-1]
  print(f"Median of height: {median}")
else:
  median = (Height[(n//2)-1]+Height[(n//2)])/2
  print(f"Median of height: {median}")
# Calculate the mean weight and print it
Weight = locality_data['Weight']
m = len(Weight)
mean_of_weight = sum(Weight)/m
print(f"Mean of weight: {mean_of_weight}")
# Calculate the median weight and print it
Weight=sorted(Weight)
if m%2!=0:
  median_of_weight = Weight[((n+1)//2)-1]
  print(f"Median of height: {median_of_weight}")
else:
  median_of_weight = (Weight[(n//2)-1]+Weight[(n//2)])/2
  print(f"Median of height: {median_of_weight}")

"""* Write a Python code to print the first three elements from the list of age values corresponding to the key 'Age'"""

# Python code to print the first three elements for the key 'Age'
print(f"Age of first three elements: {locality_data['Age'][:3]}")

"""* Write a Python code to print the last two elements of the name list if the list of values corresponding to the key 'Name' contains the element 'Rashmi' else print 'Name not found'"""

# Your code below
name = locality_data['Name']
if 'Rashmi' in name:
  print(f"Last two elements of name are: {name[-2:]}")
else :
  print("Name not found")

"""**Question 3:**

A student will not be allowed to sit in exam if his/her attendence is less than 75%.

Take following input from user

Number of classes held
Number of classes attended.
"""

# Enter your input
print("Number of classes held")
classes_held = 500

# Enter your scond input
print("Number of classes attended")
classes_attended = 100

classes_held = 500
classes_attended = 100
# Calculate the attendance percentage
percentage_of_class_attended = (classes_attended/classes_held)*100
print(f"Percentage of attendance: {percentage_of_class_attended}")

"""And print the following statements based on the condition above

* percentage of class attended
* Is student is allowed to sit in exam or not.
"""

# Your code here
if(percentage_of_class_attended<75):
  print("Student is not allowed")
else:
  print("Allowed")

"""**Question 4:**

A school has following rules for grading system:
* Below 25 - F
* 25 to 45 - E
* 45 to 50 - D
* 50 to 60 - C
* 60 to 80 - B
* Above 80 - A

Keep the left number inclusive and the right number exclusive, something like [25,45) for grade E where the set is closed at 25 and open at 45.

Write a Python code which takes marks as inputs from the user and print the corresponding grade.
"""

# Your input here
print("Enter your marks")
marks = 90

# Your code here to print the corresponding grade
marks=90
if marks<25:
  print("F")
elif marks>=25 and marks<45:
  print("E")
elif marks>=45 and marks<50:
  print("D")
elif marks>=50 and marks<60:
  print("C")
elif marks>=60 and marks<80:
  print("B")
elif marks>80:
  print("A")