# -*- coding: utf-8 -*-
"""Assignment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CkA7cBR_tA1xVqGWTAFlsHdW4flN99gq

# **Assignment 1**

**Question 1:**

You are given a sentence which reads "Wikipedia is a free online encyclopedia, created and edited by volunteers around the world and hosted by the Wikimedia Foundation."

Find the number of words in the given sentence.
"""

sentence="Wikipedia is a free online encyclopidea, created and edited by volunteers around the world and hosted by the Wikimedia Foundation."
a=sentence.count(' ')
print(a+1)

"""**Question 2:**

Write a Python code which takes a number and returns a corresponding string of hyphens. For example if the number is 3, it will return '---' , if the number is 5 it will return '-----'
"""

inputted_number=10
print('- '*inputted_number)

"""**Question 3:**

 A string can be called a safe bridge if it has no gaps in it i.e, no spaces. You are supposed to take an input from the user and print whether the string is a safe bridge or not.
"""

bridge='rahul singh'
a= bridge.count(' ')
print(a==0)
bridge='mohan'
a=bridge.count(' ')
print(a==0)

"""**Question 4:**

Count the number of D's in a string inputted by the user. This will be case insensitive.
"""

user_string="Debris was scattered all over the place in the densest region of Denmark"
print(user_string.lower().count('d'))

"""**Question 5:**

Check whether a given string is a palindrome. A palindrome is a word, number, phrase, or other sequence of characters which reads the same backward as forward, such as madam, racecar.
"""

user_string='madam'
print(user_string==user_string[::-1])