# -*- coding: utf-8 -*-
"""Assignment12 - Time and Space Complexity.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GM_2dOU99Cdb-HggVSfEHAo-1iS_NLpm

## <u>While doing this assignment only use those concepts which have been taught till now</u>

# Problem 1

Write a Python function which takes a string as an input and returns the reversed string as an output.


*   Do not use any inbuilt funtion or method. Use `for` loops only.
"""

# Write your code here
import sys
def reverse_string(text):
    reversed_text = ""
    for i in range(len(text) - 1, -1, -1):
        reversed_text = reversed_text + text[i]

    return reversed_text
string = input("Enter a string: ")
reversed_str = reverse_string(string)
print("Original String :", string)
print("Reversed String :", reversed_str)
# Memory used by original string
print("Memory of Original String:", sys.getsizeof(string), "bytes")
# Memory used by reversed string
print("Memory of Reversed String:", sys.getsizeof(reversed_str), "bytes")
# Time Complexity : O(n)?
# Space Complexity : ?

"""# Problem 2

Write a Python function which takes a list of `n` lists as an input. Each of the `n` lists have `m` non-zero positive integers each. The function should return a list which contains `n` integers corresponding to the square of the maximum of each of the `n` lists in the list of lists.

Example:
Inputs
```
n = 2
m = 3
list_of_lists = [[1, 2, 3], [5, 7, 6]]
```
Output:
```
[9, 49]
```

*   Do not use any inbuilt funtion or method. Use `for` loops only.


"""

# Write your code here
def square_of_max(list_of_lists):
    result = []

    for sublist in list_of_lists:
        maximum = sublist[0]

        for num in sublist:
            if num > maximum:
                maximum = num

        result.append(maximum * maximum)

    return result


# Example
list_of_lists = [[1, 2, 3], [5, 7, 6]]

print(square_of_max(list_of_lists))

# Time Complexity : O(n * m)
# Space Complexity : O(n)

