# -*- coding: utf-8 -*-
"""Assignment14 - Introduction to Data Visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yn0OvaRteAPX-C8cjzHjLC6AVQUU4cmp

# <u> Use only those concepts which have been taught till now </u>

## Use the file company_sales_data.csv
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd

from datetime import datetime

import matplotlib.pyplot as plt
# %matplotlib inline
df = pd.read_csv('/content/drive/MyDrive/DataSetForpython/Copy of company_sales_data.csv')

"""# <u>**Problem 1**</u>

### Plot the total profit across the months

* X label name = Month Number
* Y label name = Total profit


"""

# Your code here
plt.plot(df['month_number'], df['total_profit'])
plt.xlabel("Month Number")
plt.ylabel("Total profit")
plt.title("Total Profit Across the Months")
plt.show()

"""# <b><u>Problem 2 </u></b>

### Read face cream and facewash product sales data and show it using the bar chart. The bar chart should display the number of units sold per month for each product. Add a separate bar for each product in the same chart.
"""

df.head()

df.columns

# Your code here
# Width of each bar
bar_width = 0.35

# X-axis positions
x = np.arange(len(df['month_number']))
# Plot bars
plt.bar(x - bar_width/2, df['facecream'], width=bar_width, label='Face Cream')
plt.bar(x + bar_width/2, df['facewash'], width=bar_width, label='Face Wash')
# Labels and title
plt.xlabel("Month Number")
plt.ylabel("Units Sold")
plt.title("Face Cream and Face Wash Sales Data")
# Month numbers on x-axis
plt.xticks(x, df['month_number'])
# Legend
plt.legend()
plt.show()

"""# <b><u>Problem 3</u></b>

### Display the number of units sold per month for each product using multiline plots. (i.e. separate plotline for each product ).
"""

# Your code here
plt.plot(df['month_number'], df['facecream'], label='Face Cream')
plt.plot(df['month_number'], df['facewash'], label='Face Wash')

plt.xlabel("Month Number")
plt.ylabel("Units Sold")
plt.title("Monthly Sales of Face Cream and Face Wash")

plt.legend()

plt.show()