# -*- coding: utf-8 -*-
"""Assignment3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yXXEActjgVFaG57pf9PKMdAp6u02cFEJ

#**Assignment 3**

**Question 1:**

Another measure of average
Mode is defined as the value that appears most often in a set of data values. Mode corresponds to the most frequent value.
You are given a list of numbers and you need to calculate the mode of this list
"""

# A list containing average daily temperature over 10 days
temperatures = [34, 40, 29, 33, 42, 40, 39, 34, 34,33 ]
temp = list(set(temperatures))
print(f"Temp in list: {temp}")
temp_dict = { }
temp_dict[temp[0]]=temperatures.count(33)
temp_dict[temp[1]]=temperatures.count(34)
temp_dict[temp[2]]=temperatures.count(39)
temp_dict[temp[3]]=temperatures.count(40)
temp_dict[temp[4]]=temperatures.count(42)
temp_dict[temp[5]]=temperatures.count(29)
print(f"Dictionary of tempratures and its count: {temp_dict}")
dict_values=list(temp_dict.values())
dict_keys=list(temp_dict.keys())
max_count = max(dict_values)
count_indx = dict_values.index(max_count)
print(f"Mode: {dict_keys[count_indx]}")

"""**Question 2:**

Challenging the immutability of tuples
You are given a list of tuples.

You need to replace the last element of the last tuple
"""

# Input list of tuples
list_of_tuples = [(10,20,30),(30,40,50),(50,60,70)]
# Expected output : Replace the last element 70 with 100
# output_list = [(10,20,30),(30,40,50),(50,60,100)]
b = list(list_of_tuples[-1])
b[-1]=100
c = tuple(b)
list_of_tuples[-1]=c
print(f"Updated list of tuples: {list_of_tuples}")

"""**Question 3:**

Natural Language Processing or NLP is one of the most promising fields in Machine Learning. Most of the times in NLP we deal with the textual data (a bunch of strings). Sometimes when we are processing the text, it is a common practice to get rid of some set of stop words from our original text. By default stop words are very common words used in English language such as and, or, punctuations etc.

In this exercise, you are provided with a default set of stop words and you need to add some extra set of custom words.
"""

# A sample sentence

sentence = 'Hello, good morning folks! Today we will announce the half yearly performance results of the company. Due to the ongoing COVID-19 pandemic, our profits have declined by 60% as compared to the last year'

# Print your sentence

# Default set of stop words
stop_words = {"i", "me", "my", "myself", "we", "our", "ours", "ourselves", "you", "your", "yours", "yourself",
              "yourselves", "he", "him", "his", "himself", "she", "her", "hers", "herself", "it", "its", "itself",
              "they", "them", "their", "theirs", "themselves", "what", "which", "who", "whom", "this", "that",
              "these", "those", "am", "is", "are", "was", "were", "be", "been", "being", "have", "has", "had",
              "having", "do", "does", "did", "doing", "a", "an", "the", "and", "but", "if", "or", "because",
              "as", "until", "while", "of", "at", "by", "for", "with", "about", "against", "between", "into",
              "through", "during", "before", "after", "above", "below", "to", "from", "up", "down", "in", "out",
              "on", "off", "over", "under", "again", "further", "then", "once", "here", "there", "when", "where",
              "why", "how", "all", "any", "both", "each", "few", "more", "most", "other", "some", "such", "no",
              "nor", "not", "only", "own", "same", "so", "than", "too", "very", "s", "t", "can", "will", "just",
              "don", "should", "now"}

# Update the set of stop words by adding the custom stop words

custom_stop_words = ["hello","good","morning","half","yearly"]
# Your code here


# Print the stop words in a sorted manner

custom_stop_words = ["hello","good","morning","half","yearly"]
stop_words.update(set(custom_stop_words))

print(stop_words)

# # Do the same task another way. Keep in mind to use the original set of stop_words for this piece of code
custom_stop_words = ["hello","good","morning","half","yearly"]
stop_words = {"i", "me", "my", "myself", "we", "our", "ours", "ourselves", "you", "your", "yours", "yourself",
              "yourselves", "he", "him", "his", "himself", "she", "her", "hers", "herself", "it", "its", "itself",
              "they", "them", "their", "theirs", "themselves", "what", "which", "who", "whom", "this", "that",
              "these", "those", "am", "is", "are", "was", "were", "be", "been", "being", "have", "has", "had",
              "having", "do", "does", "did", "doing", "a", "an", "the", "and", "but", "if", "or", "because",
              "as", "until", "while", "of", "at", "by", "for", "with", "about", "against", "between", "into",
              "through", "during", "before", "after", "above", "below", "to", "from", "up", "down", "in", "out",
              "on", "off", "over", "under", "again", "further", "then", "once", "here", "there", "when", "where",
              "why", "how", "all", "any", "both", "each", "few", "more", "most", "other", "some", "such", "no",
              "nor", "not", "only", "own", "same", "so", "than", "too", "very", "s", "t", "can", "will", "just",
              "don", "should", "now"}
new = set(custom_stop_words)
print((list(sorted(stop_words | new))))

"""**Question 4:**

Write a Python script to check whether a given key already exists in a dictionary. If it does, drop that key from the dictionary. If it does not, add that key and corresponding value to the dictionary
"""

# Your dictionary
employee_dict = {'Name':'Sanket','Skills':['Python','Machine Learning','Deep Learning'],'Band':6.0,
                 'Promotion Year':[2016,2018,2020]}

# Check if the key 'Employee_ID' is present in the dictionary.

employee_dict = {'Name':'Sanket','Skills':['Python','Machine Learning','Deep Learning'],'Band':6.0,
                 'Promotion Year':[2016,2018,2020]}
employee_dict.get('Employee_ID','Key is not available')

# If not present add this key to this dictionary and the corresponding value to be 4503233
employee_dict['Employee_ID']=4503233
print(employee_dict)

# Check if the key 'Band' is present in the dictionary.

employee_dict.get('Band','Key not available')

# If present, drop this key from the dictionary



employee_dict.pop('Band')
print(employee_dict)