# -*- coding: utf-8 -*-
"""Assignment 10 - Introduction to NumPy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pY1R1JirfnP_aeorEmBL3h6xSQoyLu42

#<u>**Problem 1**</u>

### Construct a 2-D 10*10 matrix with the diagonal elements equal to zero and all the other elements equal to 1
"""

import numpy as np
#Method 1
a = np.ones((10,10),dtype = 'int64')
for i in range(10):
  for j in range(10):
    if i == j:
      a[i][j] = 0
print(a)

import numpy as np
#Method 2
a = np.ones((10,10),dtype = 'int64')
np.fill_diagonal(a,0)
print(a)

"""# <u>**Problem 2**</u>

### Construct a list of first 100 natural numbers. Find the square of each number and output that in the form of another list containing 10 lists each.

"""

import numpy as np
natural_number = np.arange(1,101,(1))
np.array_split(np.multiply(natural_number,natural_number),10)

"""#<u>**Problem 3**</u>

### You are given an image below. Experiment with the numpy slice operation to only get the face of the person in the image
"""

import numpy as np

# Importing data from the skimage library. Don't worry much about it
 from skimage import data
 camera = data.camera()

# Camera is 2-D array object
camera.shape

camera

# You can plot the camera object and see the image
import matplotlib.pyplot as plt
plt.imshow(camera)

# Perform your slice operation here to get the face of the person

import matplotlib.pyplot as plt
# Crop the face
face = camera[70:200, 140:275]
# Display the cropped face
plt.imshow(face, cmap='gray')
plt.axis('off')
plt.show()