# -*- coding: utf-8 -*-
"""Assignment8- Functions and Methods.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IRhRgwTvYHZsLITol3Fv9YxDAxpBxGeI

# <u> Problem 1</u>

### Write a function which takes the excel column name as an input and returns the corresponding column number. A few examples are :

* column name = <code>'J'</code> , column number = <code>10</code>
* column name = <code>'AP'</code> , column number = <code>42</code>
* column name = <code>'AAA'</code>, column number = <code>703</code>
"""

def get_excel_column_number(column_name):
  '''
  This functions returns the corresponding column number for an excel column name
  '''
  # Step 1 : Get the dictionary mapping
  alphabets = ['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z']
  number = range(1,27)
  # Zip them together
  dictionary = dict(zip(alphabets,number))
  # Step 2 : Starting from the righmost character of the column name, keep adding the column number
  column_number = 0;
  for i, char in enumerate(reversed(column_name)):
    column_number =  column_number + dictionary[char]*(26**i)
  return column_number

# Check
get_excel_column_number('J')

# Check
get_excel_column_number('AP')

get_excel_column_number('AAA')

"""# <u> Problem 2 </u>

### Write a Python function which takes a sentence and a length value as inputs and returns the counts of those words from the sentence whose length is equal to the provided input length value.

### Suppose if the input for the length value is 5, it will return the count of all those words which are of length 5
"""

marvel_quote = "The world has changed and none of us can go back. All we can do is our best, and sometimes the best that we can do is to start over."

# Your function below. Make sure to remove the special characters such as full stop and comma.
def fixed_length_word_counts(sentence, length=5):
  '''
  This function returns the count of the words with the given input length
  '''
  # Your code below
  sentence = sentence.replace(",","").replace(".","")
  word = [i for i in sentence.split() if len(i)==length]
  return len(word)

# Check on the sample sentence
print(f"Number of words greater than the length of 5:")
fixed_length_word_counts(marvel_quote)