# -*- coding: utf-8 -*-
"""Assignment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xoC93aWU1xnXYqDTazRQ5flw9w4DNCWw

# **Assignment 2**

**Question 1:**
"""

temp = [34, 40, 29, 33, 42, 37, 39]
max = temp.index(42)
min = temp.index(29)
temp[min],temp[max]=temp[max],temp[min]
print(temp)

"""**Question 2**"""

# Calculate the mean of the product prices
prod_price_list = [400, 250, 800, 550, 600, 820, 720, 15000, 360,250]
mean=sum(prod_price_list)/len(prod_price_list)
print(f"Mean:{mean}")
#Median
prod_price_list = sorted(prod_price_list)
n=len(prod_price_list)
median = (prod_price_list[(n//2)-1]+prod_price_list[n//2])/2
print(f"Median:{median}")

"""**Question 3**"""

tech_companies = ['Qualcomm','Google','Apple',['Nvidia','Cisco','Samsung']]
tech = tech_companies.pop(3)
tech_companies.extend(tech)
print(f"New list: {tech_companies}")