# -*- coding: utf-8 -*-
"""Assignment15 - Pandas Operations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-s1v4S-RLXmICFFUHlX71NoH-Y7O7A8v

## <u> Use only those concepts which have been taught till now </u>

# <b> Problem 1: Import Pandas and Numpy in the notebook </b>
"""

import pandas as pd
import numpy as np

"""# <b> Problem 2 : Load the automobile_data.csv kept in the shared folder"""

df = pd.read_csv('/content/drive/MyDrive/DataSetForpython/automobile_data.csv')

"""# <b> Problem 3 : Do a basic inspection and print the first and last 15 rows of your dataframe"""

df.head(15)

df.tail(15)

"""# <b>Problem 4 : You need to clean the data a little bit now. Replace all column values with the values <code>?</code> and <code>n.a</code> with <code>NaN</code>"""

df.replace(['?', 'n.a'], 'NaN', inplace=True)
df.tail(15)

"""# <b>Problem 5 : Print the company name which manufactured the most expensive car. Also print the price of the most expensive car"""

df['price'] = pd.to_numeric(df['price'], errors='coerce')
df[df['price'] == df['price'].max()]

"""# <b>Problem 6 : Calculate maximum horsepowers for each company. </b>"""

df['horsepower'] = pd.to_numeric(df['horsepower'], errors='coerce')
df.groupby('make')['horsepower'].max()

"""# <b> Problem 7 : Print the total number of cars manufactured by each company"""

df.groupby(['make']).size()

"""# <b> Problem 8 : Create a new column for the updated price. This updated price will be calculated on top of the given price - if the engine is in front, price will be same else if the engine is in rear, price will be doubled </b>

"""

df['updated_price'] = df['price']
df.loc[df['engine-location'] == 'rear', 'updated_price'] *= 2

"""# <b>Problem 9 : Sort the dataframe by car and price columns"""

df.sort_values(by=['make', 'price'])

"""# <b> Problem 10 : Create a new column which stores the number of doors in a car as integers."""

df['number_of_doors'] = df['num-of-doors'].replace({'two': 2, 'four': 4}).astype('Int64')
df.head()

"""# <b>Problem 11 : Concatenate the two data frames given below firstly row wise and secondly column wise.</b>

<code>GermanCars = {'Company': ['Ford', 'Mercedes', 'BMV', 'Audi'], 'Price': [23845, 171995, 135925 , 71400]}</code>

<code>japaneseCars = {'Company': ['Toyota', 'Honda', 'Nissan', 'Mitsubishi '], 'Price': [29995, 23600, 61500 , 58900]}</code>
"""

GermanCars = {
    'Company': ['Ford', 'Mercedes', 'BMV', 'Audi'],
    'Price': [23845, 171995, 135925, 71400]
}
JapaneseCars = {
    'Company': ['Toyota', 'Honda', 'Nissan', 'Mitsubishi'],
    'Price': [29995, 23600, 61500, 58900]
}
df1 = pd.DataFrame(GermanCars)
df2 = pd.DataFrame(JapaneseCars)
concat = pd.concat([df1, df2], axis=0)
print(concat)